# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mtgrsbed_matrix <- function(file, n, cls, af, scale, S, nthreads = 1L, MG = 64L, JB = 1024L, TB = 32L) {
    .Call(`_qgtools_mtgrsbed_matrix`, file, n, cls, af, scale, S, nthreads, MG, JB, TB)
}

mtgrsbed_matrix_f <- function(file, n, cls, af, scale, S, nthreads = 1L, MG = 64L, JB = 1024L, TB = 32L) {
    .Call(`_qgtools_mtgrsbed_matrix_f`, file, n, cls, af, scale, S, nthreads, MG, JB, TB)
}

